# Generated by Django 2.2.10 on 2021-02-01 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nouvelle_Relance', models.CharField(choices=[('nouvelle procédure', 'Nouvelle procédure'), ('relance procédure', 'Relance procédure')], max_length=30)),
                ('N_Dossier', models.CharField(max_length=10)),
                ('A_N_Dossier', models.CharField(blank='false', max_length=10)),
                ('Designation', models.TextField(max_length=60)),
                ('Type_Operation', models.CharField(choices=[('consultation', 'Consultation'), ('gré à gré', 'Gré à Gré')], max_length=60)),
                ('Nom_Agent_Tech', models.TextField(max_length=60)),
                ('date_Fich_Tech', models.DateTimeField()),
                ('Fich_Tech_valid', models.FileField(upload_to='Fiche/')),
                ('date_Lance', models.DateTimeField()),
                ('date_Ouvert', models.DateTimeField()),
                ('PV_Eval', models.FileField(upload_to='Evaluation/')),
                ('PV_Ouvert', models.FileField(upload_to='Ouverture/')),
                ('System_Eval', models.CharField(choices=[('système de notation', 'Système de notation'), ('le moins Disant', 'Le moins Disant')], max_length=30)),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Iden_Ope', models.TextField(blank='false', max_length=200)),
                ('Raison_Soci', models.TextField(blank='false', max_length=200)),
                ('Statut_Juri', models.TextField(blank='false', max_length=200)),
                ('N_Tele', models.CharField(blank='false', max_length=12)),
                ('N_Fax', models.CharField(blank='false', max_length=12)),
                ('Email', models.EmailField(blank='false', max_length=254)),
                ('Con_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marche.Consultation')),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
